#!/bin/bash

#PBS -N d2q9-bgk
#PBS -joe
#PBS -o d2q9-bgk.out
#PBS -q teaching
#PBS -l epilogue=~ggdagw/epilogue.sh
#PBS -l nodes=4:ppn=16,walltime=00:05:00

#! Mail to user if job aborts
#PBS -m a

#! application name
application="./d2q9-bgk"

#! Run options for the application
options="input_1024x1024.params obstacles_1024x1024.dat"

module="module load languages/intel-compiler-15"


###############################################################
### You should not have to change anything below this line ####
###############################################################

#! change the working directory (default is home directory)

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID
echo This jobs runs on the following machines:
echo `cat $PBS_NODEFILE | uniq`
 
#! Create a machine file for MPI
cat $PBS_NODEFILE | uniq > machine.file.$PBS_JOBID
# cat $PBS_NODEFILE > machine.file.$PBS_JOBID

numnodes=`wc $PBS_NODEFILE | awk '{ print $1 }'`

export OMP_NUM_THREADS=2
export KMP_AFFINITY=compact


# export KMP_AFFINITY=granularity=fine,compact,1,0

#! Run the parallel MPI executable (nodes*ppn)
mpirun -np 32 -loadbalance --cpus-per-proc 2 -machinefile machine.file.$PBS_JOBID $application $options 

